/control/verbose 1
/process/em/verbose 1
/process/had/verbose 1
/geometry/source detector.tg

/run/initialize
/process/list
#/process/inactivate eIoni e-


/gps/particle gamma
/gps/energy 662 keV
/gps/position 0 20 0 cm
/gps/direction 0 -1 0


#/vis/open VRML2FILE
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 100000
/run/beamOn 10

/vis/viewer/flush
/vis/viewer/update
 
#/vis/open HepRepFile
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/add/trajectories

/tracking/verbose 1
/run/beamOn 10

/vis/disable
/tracking/verbose 0
/analysis/setFileName Detector_400.root
/run/verbose 1
/run/printProgress 100
/run/beamOn 100000