/control/verbose 0
/process/em/verbose 0
/process/had/verbose 0

/run/initialize
/geometry/test/run
/vis/open 
/vis/drawVolume
/vis/scene/add/axes 0 0 0 20 cm
/vis/viewer/set/style surface
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/refresh

/gps/source/add 1
/gps/particle gamma
/gps/energy 1 MeV
/gps/position 0 0 -10 cm
/gps/direction 0 0 1


/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate
/run/beamOn 20
/vis/viewer/refresh
