/control/verbose 0
/process/em/verbose 0
/process/had/verbose 0

/run/initialize

/vis/open 
/vis/drawVolume
/vis/scene/add/axes 0 0 0 10 cm
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/refresh

/gps/source/add 1
/gps/particle gamma
/gps/energy 5 MeV
/gps/position 10 0 0 cm
/gps/direction -1 0 0

/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate
#/vis/viewer/set/viewpointVector 1 1 1
/run/beamOn 100
/vis/viewer/refresh
