/control/verbose 0
/process/em/verbose 0
/process/had/verbose 0

/run/initialize
/geometry/test/run

/vis/open 
/vis/drawVolume
/vis/scene/add/axes 0 0 0 10 cm
/vis/viewer/set/style surface


/vis/viewer/set/viewpointVector 0 0 0
/vis/viewer/set/background white
/vis/viewer/flush

#/gps/source/add 1
/gps/particle gamma
/gps/energy 662 keV
/gps/position 0 10 0 cm
/gps/direction 0 -1 0

#/gps/ang/type iso
#/gps/ang/rot1 1 0 0
#/gps/ang/rot2 0 0 -1
#/gps/ang/mintheta 0 rad
#/gps/ang/maxtheta 0.2 rad

/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/viewpointVector 0 0 0
/run/beamOn 50000
/vis/viewer/refresh
