/control/verbose 1
/process/em/verbose 1
/process/had/verbose 1
/geometry/source detector.tg

/run/initialize
/process/list
#/process/inactivate eIoni e-

/gps/source/add 1
/gps/particle gamma
/gps/energy 662 keV
/gps/position 0 50 0 cm
/gps/direction 0 -1 0

/vis/open 
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 10
/run/beamOn 10
 
/vis/open HepRepFile
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/add/trajectories

/tracking/verbose 2
/run/beamOn 10

/vis/disable
/tracking/verbose 0
/analysis/setFileName sucrose.root
/run/verbose 2
/run/printProgress 100
/run/beamOn 50000 
