/control/verbose 1
/process/em/verbose 1
/process/had/verbose 1

/geometry/source detector.tg
/run/initialize
/process/list
#/process/inactivate eIoni e-

/gps/source/add 1
/gps/particle mu+
#/gps/ang/type iso
/gps/energy 4 GeV
/gps/position 0 100 0 cm
/gps/direction 0 -1 0

/vis/open VRML2FILE
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 10
/run/beamOn 10

/vis/open HepRepFile
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/add/trajectories

# turn on detailed information about tracking
/tracking/verbose 2
# dump a few events on screen for debugging
/run/beamOn 10

# turn off screen printing for fast simulation 
/vis/disable
/tracking/verbose 0
# turn on data recording
/analysis/setFileName muonPlus.root
# turn on progress report
/run/verbose 2
/run/printProgress 10000
# start simulation
/run/beamOn 50000
