/control/verbose 0
/process/em/verbose 0
/process/had/verbose 0

/run/initialize
/geometry/test/run

/vis/open TSG_FILE
/vis/drawVolume
/vis/viewer/zoom 1.5
/vis/viewer/set/style surface
/vis/viewer/set/viewpointThetaPhi 45 45
/vis/viewer/flush

/gps/particle gamma
/gps/energy 662 keV
/gps/position 0 0 -50 cm
/gps/direction 0 0 1

/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate
/run/beamOn 10
/vis/viewer/refresh  