/control/verbose 0
/process/em/verbose 1
/process/had/verbose 0
/geometry/source detector.tg

/run/initialize
/process/list
#/process/inactivate eIoni e-

/gps/source/add 1
/gps/particle gamma
/gps/energy 5 MeV
/gps/position 0 0 -5 cm
/gps/direction 0 0 1
/vis/open VRML2FILE
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 10
/run/beamOn 10
 
/vis/open HepRepFile
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/add/trajectories

/tracking/verbose 2
/run/beamOn 10

/vis/disable
/tracking/verbose 0
/analysis/setFileName MeVgamma_drop.root
/run/verbose 2
/run/printProgress 100
/run/beamOn 500 
