/control/verbose 1
/process/em/verbose 1
/process/had/verbose 0
/geometry/source detector.tg
/run/initialize
/process/list

/process/inactivate eIoni e-

/gps/particle e-
/gps/energy 1 MeV
/gps/ang/type iso
/gps/ang/minphi 180 deg
/gps/ang/maxphi 270 deg
/gps/ang/mintheta 40 deg
/gps/ang/maxtheta 150 deg

/vis/open VRML2FILE
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 10
/run/beamOn 10
 
/vis/open HepRepFile
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/add/trajectories

/tracking/verbose 2
/run/beamOn 10

/vis/disable
/tracking/verbose 0
/analysis/setFileName 1MeV_e-.root
/run/verbose 2
/run/printProgress 100
/run/beamOn 500
